repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
-   repo: local
    hooks:
      - id: build_doc
        name: build docs
        entry: python ./build_docs.py
        language: python
        files: ^qute/
