name: qute-env

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pip
  - natsort
  - tifffile
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - cudatoolkit=11.3
  - pyyaml
  - pip:
      - pytorch-lightning
      - lightning-bolts
      - lightning-flash[image]
      - monai

