name: qute-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - natsort
  - tifffile
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - cudatoolkit=11.3
  - conda-forge::pytorch-lightning
  - conda-forge::torchmetrics
  - conda-forge::lightning-flash[image]
  - conda-forge::ray-tune
  - pyyaml
  - pdoc3
  - pip:
      - lightning-bolts
      - monai
