name: qute

channels:
  - pytorch
  - fastchan
  - defaults

dependencies:
  - python=3.9
  - pip>=21.0
  - tifffile>=2021.3.5
  - cudatoolkit=11.3
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - fastchan::fastai

  - pip:
      - pytorch-lightning
      - lightning-bolts
      - monai

