[tool.poetry]
name = "qute"
version = "0.1.0"
description = "Deep learning workflow manager."
authors = ["Aaron Ponti <aaron.ponti@bsse.ethz.ch>, Andreas Cuny <andreas.cuny@bsse.ethz.ch>"]
license = "Apache-2.0"
readme = "README.md"
classifiers=[
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Education",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Education",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
torch = ">=2.0.0, !=2.0.1"
nvidia-cublas-cu12="*"
nvidia-cuda-cupti-cu12="*"
nvidia-cuda-nvrtc-cu12="*"
nvidia-cuda-runtime-cu12="*"
nvidia-cudnn-cu12="*"
nvidia-cufft-cu12="*"
nvidia-curand-cu12="*"
nvidia-cusolver-cu12="*"
nvidia-cusparse-cu12="*"
nvidia-nccl-cu12="*"
nvidia-nvtx-cu12="*"
lightning-bolts = ">=0.6.0.post1"
tifffile = ">=2023.2.3"
natsort = ">=8.2.0"
torchmetrics = ">=0.11.1"
torchvision = ">=0.15"
tensorboard = ">=2.11.2"
scikit-image = ">=0.19.3"
torchio = ">=0.18.87"
pytorch-lightning = ">=2.0.1.post0"
ray = {extras = ["tune"], version = ">=2.3.1"}
protobuf = "3.20.3"             # Required for ray[tune] 2.3.1
monai = ">=1.2.0"
kornia = ">=0.7.0"

[tool.poetry.group.dev.dependencies]
pdoc3 = ">=0.10.0"
isort = ">=5.12.0"
black = ">=23.1.0"
pytest = ">=7.2.1"
torch-tb-profiler = ">=0.4.1"
types-pyyaml = ">=6.0.12.5"
mypy = ">=1.0.0"
types-requests = ">=2.28.11.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
