[tool.poetry]
name = "qute"
version = "0.1.0"
description = "Deep learning workflow manager."
authors = ["Aaron Ponti <aaron.ponti@bsse.ethz.ch>, Andreas Cuny <andreas.cuny@bsse.ethz.ch>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.13.1"
lightning-bolts = "^0.6.0.post1"
monai = "^1.1.0"
tifffile = "^2023.2.3"
natsort = "^8.2.0"
torchmetrics = "^0.11.1"
torchvision = "^0.14.1"
pytorch-lightning = {extras = ["extra"], version = "^1.9.0"}

[tool.poetry.group.dev.dependencies]
pdoc3 = "^0.10.0"
isort = "^5.12.0"
black = "^23.1.0"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
